spring:
  profiles:
    # 获取开发环境中农的配置文件，环境配置文件必须以 application-xxx.yml 的命名格式
    active: dev
  datasource:
    url: jdbc:mysql://118.25.49.178:3306/seckill?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: yxf@3302
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml