spring:
  profiles:
    # 获取开发环境中农的配置文件，环境配置文件必须以 application-xxx.yml 的命名格式
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://118.25.49.178:3306/seckill?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: yxf@3302
      # 配置初始化大小/最小/最大[仅用于测试，生成环境需要修改哦]
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 一个连接在池中最小生存的时间
      time-between-eviction-runs-millis: 300000
      # 指定获取连接时连接校验的sql查询语句
      validation-query: SELECT 'x'
      # 验证连接的有效性
      test-while-idle: true
      # 获取链接时验证，会影响性能(不建议 true)
      test-on-borrow: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml

# pagehelper
pagehelper:
  helper-dialect: mysql
  #  分页参数合理化，默认false禁用 .启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  #  用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  support-methods-arguments: true
  # 设置为true时，使用RowBounds分页会进行count查询，默认=false
  row-bounds-with-count: true